### ISSUE TITLE
Template code not inserted into HTML area in Moodle 3.3

### ISSUE THREAD

**Issue by SamStegers** [sharpchi/moodle-atto_templates4u#1]
Hi,

I am trying to use the ATTO Templates plugin in Moodle 3.3 but I am experiencing an issue.

Steps:

1. create template in settings of the plugin --> this works, see below for used code
<img width="1084" alt="schermafbeelding 2017-06-29 om 10 56 40" src="https://user-images.githubusercontent.com/1179956/27679715-c7b46920-5cb9-11e7-9818-9e1e513c37f5.png">

2. select template in ATTO Editor --> no problem there

3. preview rendered template --> works correctly, see below
<img width="597" alt="schermafbeelding 2017-06-29 om 10 56 16" src="https://user-images.githubusercontent.com/1179956/27679777-fbd0efee-5cb9-11e7-85c4-3c89e2f38e1e.png">

4. click insert button --> no HTML code is inserted into the HTML area.

With regards,
Sam

**Comment by sharpchi** [comment]
Thanks Sam. I've not yet tested in M3.3. I'm not going to be able to for a few days. But could you try with something simpler? e.g. just text. 
I tried your template in M3.2 and it worked fine for me.

Which kind of text area were you trying to add it to? e.g. Label, Page, Profile etc

Do you have any filters installed that may be interfering?

**Comment by SamStegers** [comment]
Hello Mark,

I have tried the plugin in a vanilla Moodle 3.2.2+ (no filters) and there I get the same results. I have also tried with a simple 'Hello World' template and tried to use the template in Topic description, Label, Page, Lesson but I cannot get it to insert the code. The preview works fine as it does in Moodle 3.3.

With regards,
Sam

**Comment by sharpchi** [comment]
You using any particular flavour of browser? Does the developer console in the browser show any errors?

**Comment by sharpchi** [comment]
Not heard anything for a while. Closing the job. Let me know if this is still the case with the latest version of the plugin.
