### ISSUE TITLE
Problems with inserting on Mac

### ISSUE THREAD

**Issue by neeesn** [sharpchi/moodle-atto_templates4u#12]
On Mac in chrome we can choose the Template, but its not inserterd into the text field.
We are using the newest version of the plugin and is on 3.10.6 Moodle

**Comment by sharpchi** [comment]
Sorry to hear that. Have you tested the same action on different browser/os to be certain it's a mac issue? I don't have a mac, so I have no way of testing. But if it's a problem with something in Moodle or with the template you've created, more information would be very helpful. In particular, exactly which field in which activity, and the template you're trying to insert.
thanks

**Comment by neeesn** [comment]
Hi, sorry for the late reply.
It seems that an update to Chrome has cleared the error. 
The error was that in the editor you were able to click and select the template, but it was not inserted into the editor field. 

I have just tested on a Macbook Air in Chrome 96.0.4664.55 and cannot replicate the error. 

Im closing the issue again.
