### ISSUE TITLE
Not working when inserting <button> into template

### ISSUE THREAD

**Issue by imatotek** [sharpchi/moodle-atto_templates4u#2]
Hi!

I have used template to insert templates for different css styles, and I have tried to use to insert following code:
<button class="btn btn-default collapsed" data-target="#transk1" data-toggle="collapse" type="button">Transkript</button>
 <div id="transk1" style="height: 0px;" class="collapse">
       <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
 </div>
But, it `inserts` only this code:
Transkript
<div style="height:0px;" class="collapse">
  <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit</p>
</div>

It disregard’s part with <button>. Is this a bug or feature? Moodle version is 3.3.3+ (200171123), and Templates plugin is 3.4 (2017103001).

Ivica

**Comment by sharpchi** [comment]
Hi, it's not clear what the problem is from your description. I've tried inserting a `<button>` HTML tag and this prints out ok:
![image](https://user-images.githubusercontent.com/3774280/73649946-d8783d80-4678-11ea-9189-c2e221120be4.png)
Please retry with the latest version
