### ISSUE TITLE
some css inline style information gets dropped when inserting a template

### ISSUE THREAD

**Issue by stemiwe** [sharpchi/moodle-atto_templates4u#3]
the templates plugin ignores some css inline style tags, while keeping others.

for example, i want to insert this template:

```
<div style="display:flex">
<div style="width: 300px">
  <img src="mypicture" style="width:80%;"></div>
```

but what actually gets inserted is:

```
<div>
<div style="width: 300px">
  <img src="mypicture"></div>
```

so the **display:flex** and **width:80%** inline style info gets dropped, while the **width:300px** inline style info works
  
is there a reason why the template plugin drops some css inline style information, but keeps others?

**Comment by sharpchi** [comment]
I've tested this, and it doesn't seem to happen for me - at least in Moodle 3.8
![image](https://user-images.githubusercontent.com/3774280/73649726-56881480-4678-11ea-876b-f68f7a662d42.png)
